default_language_version:
  python: "3.8"
default_install_hook_types: [commit-msg, pre-commit]
repos:
  - repo: https://github.com/compilerla/conventional-pre-commit
    rev: v3.1.0
    hooks:
      - id: conventional-pre-commit
        stages: [commit-msg]
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.5.0
    hooks:
      - id: check-ast
      - id: check-case-conflict
      - id: check-toml
      - id: debug-statements
      - id: end-of-file-fixer
      - id: mixed-line-ending
      - id: trailing-whitespace
  - repo: https://github.com/charliermarsh/ruff-pre-commit
    rev: "v0.3.2"
    hooks:
      - id: ruff
        args: ["--fix"]
      - id: ruff-format
  - repo: https://github.com/sourcery-ai/sourcery
    rev: v1.15.1b41
    hooks:
      - id: sourcery
        args: [--diff=git diff HEAD, --no-summary]
  - repo: https://github.com/codespell-project/codespell
    rev: v2.2.6
    hooks:
      - id: codespell
        additional_dependencies:
          - tomli
        exclude: >
          (?x)^(
              .*\.json |.*\.svg |docs/changelog.rst
          )$
  - repo: https://github.com/asottile/blacken-docs
    rev: 1.16.0
    hooks:
      - id: blacken-docs
  - repo: https://github.com/pre-commit/mirrors-prettier
    rev: "v4.0.0-alpha.8"
    hooks:
      - id: prettier
        exclude: "_templates|.git"
  #   - repo: https://github.com/thibaudcolas/curlylint
  #     rev: v0.13.1
  #     hooks:
  #       - id: curlylint
  #         args: ["--format", "stylish"]
  - repo: https://github.com/python-formate/flake8-dunder-all
    rev: v0.3.1
    hooks:
      - id: ensure-dunder-all
        exclude: "test*|examples*|tools"
        args: ["--use-tuple"]
  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: "v1.6.1"
    hooks:
      - id: mypy
        exclude: "tools|docs"
        additional_dependencies:
          [
            sqlalchemy>=2.0.20,
            "sanic[ext]",
            fastapi,
            litestar,
            quart,
            flask,
            httpx,
            time-machine,
            pytest,
            pytest-asyncio,
            pytest-lazy-fixture,
            pytest-mock,
            pytest-timeout,
          ]
  - repo: https://github.com/RobertCraigie/pyright-python
    rev: v1.1.353
    hooks:
      - id: pyright
        additional_dependencies:
          [
            sqlalchemy>=2.0.20,
            "sanic[ext]",
            fastapi,
            litestar,
            quart,
            flask,
            httpx,
            time-machine,
            pytest,
            pytest-asyncio,
            pytest-lazy-fixture,
            pytest-mock,
            pytest-timeout,
          ]
  - repo: https://github.com/sphinx-contrib/sphinx-lint
    rev: "v0.9.1"
    hooks:
      - id: sphinx-lint
